server:
  port: 9000
spring:
  web:
    resources:
      static-locations: classpath:/static/
  http:
    encoding:
      charset: UTF-8
  datasource:
    url: jdbc:mysql://${ip}:3306/course_selection?serverTimezone=GMT%2B8
    username: root
    password: 112233
    driver-class-name: com.mysql.cj.jdbc.Driver
ip: localhost